---
title: "map_figures"
author: "Lynndsay Terpsma"
date: "2025-04-02"
output: html_document
---


## Interactive Map with Leaflet ##
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(leaflet)
library(mapview)
library(htmltools)
library(leaflet.extras)
```

```{r}
iconbmsc <- awesomeIcons(
  icon = "circle",
  iconColor = '#FFFFFF',
  library = "fa",
  markerColor = "black")

iconbmscdock <- awesomeIcons(
  icon = "circle",
  iconColor = '#FFFFFF',
  library = "fa",
  markerColor = "red")

iconwestgov <- awesomeIcons(
  icon = "circle",
  iconColor = "#FFFFFF",
  library = "fa",
  markerColor = "red")

iconhealth <- awesomeIcons(
  icon = "circle",
  iconColor = "#FFFFFF",
  library = "fa",
  markerColor = "red")

compassicon <- makeIcon(
  iconUrl = "https://freesvg.org/img/CompassRose.png",
  iconWidth = 100, iconHeight = 100
)
```


```{r}
map <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addLabelOnlyMarkers(
    lng = -125.1346, lat = 48.83552,
    label = HTML("Bamfield Marine<br>Science Centre"),
    labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE, direction = "right", 
                                style = list( 
                                  "color" = "black",
                                  "font-weight" = "bold",
                                  "font-size" = "10px", 
                                  "background" = "white",
                                  "padding" = "3px", 
                                  "border-radius" = "5px"
                                  ))) %>%
  addAwesomeMarkers(
    lng = -125.13543, lat = 48.83552,
    icon = iconbmsc) %>%
  addAwesomeMarkers(
    lng = -125.13674, lat = 48.83326,
    label = "BMSC South Dock",
    icon = iconbmscdock,
    labelOptions = labelOptions(noHide = TRUE, direction = "right",
                                style = list( 
                                  "color" = "black",
                                  "font-weight" = "bold",
                                  "font-size" = "10px", 
                                  "background" = "white",
                                  "padding" = "3px", 
                                  "border-radius" = "5px"))) %>%
  addAwesomeMarkers(
      lng = -125.13988, lat = 48.82896,
      label = "West Government Dock",
      icon = iconwestgov,
      labelOptions = labelOptions(noHide = TRUE, direction = "left",
                                  style = list( 
                                  "color" = "black",
                                  "font-weight" = "bold",
                                  "font-size" = "10px", 
                                  "background" = "white",
                                  "padding" = "3px", 
                                  "border-radius" = "5px"))) %>%
  addAwesomeMarkers(
      lng = -125.13719, lat = 48.82711,
      label = "Island Health Dock",
      icon = iconhealth,
      labelOptions = labelOptions(noHide = TRUE, direction = "right",
                                  style = list( 
                                  "color" = "black",
                                  "font-weight" = "bold",
                                  "font-size" = "10px", 
                                  "background" = "white",
                                  "padding" = "3px", 
                                  "border-radius" = "5px"))) %>%
  addScaleBar(
    map,
    position = "topright"
  )
scaleBarOptions(
  maxWidth = 100,
  metric = TRUE,
  updateWhenIdle = TRUE
)
map
```

```{r}
mapshot(map, file = "mapfigure_zoomedin.png")
```


```{r}
map2 <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addAwesomeMarkers(
      lng = -125.13543, lat = 48.83552,
      icon = iconbmsc,
      label = "Bamfield Marine Science Centre",
      labelOptions = labelOptions(noHide = TRUE, direction = "left",
                                  style = list( 
                                  "color" = "black",
                                  "font-weight" = "bold",
                                  "font-size" = "10px", 
                                  "background" = "white",
                                  "padding" = "3px", 
                                  "border-radius" = "5px"))) %>%
  setView(lng = -123.53238, lat = 49.05492, zoom = 7)
map2
```

```{r}
mapshot(map2, file = "mapfigure_zoomedout.png")
```


## Static Map with ggplot ##

```{r setup2, include = FALSE}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(cowplot)
library(ggrepel)
library(rnaturalearthhires)
library(maptiles)
library(patchwork)
```

```{r world map setup}
Bamfield <- data.frame(name = "Study Area", lon = -125.14078, lat = 48.83336)
Bamfield_sf <- st_as_sf(Bamfield, coords = c("lon", "lat"), crs = 4326)

bam_coords <- st_coordinates(Bamfield_sf)
bam_point_df <- data.frame(x=bam_coords[,1], y = bam_coords[,2])
```

```{r world map}
world <- ne_countries(scale = "medium", returnclass = "sf")

world_map <- ggplot() +
  geom_sf(data = world, fill = "gray90", color = "gray50") +
  geom_point(data = bam_point_df, aes(x=x, y=y), shape = 0, color = "black", size = 3, stroke = 1) +
  theme_minimal() +
  annotation_scale(location = "bl", width_hint = 0.3, line_width = 0.5, text_cex = 0.7) +
  annotation_north_arrow(location = "tl", which_north = "true", style = north_arrow_orienteering, width = unit(1, "cm"), height = unit(1, "cm"), pad_x = unit(0.25, "cm")) +
  coord_sf(xlim = c(-170, -45), ylim = c(30, 80)) +
  labs(x = "Longitude", y = "Latitude") +
  ggtitle("a) study site location (world map)") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

world_map
```

```{r bamfield map setup}
sites <- data.frame(
  name = c("BMSC South Dock", "West Government Dock", "Island Health Dock"),
  lon = c(-125.13674, -125.13988, -125.137045),
  lat = c(48.833226, 48.82869, 48.82711)
)

sites_sf <- st_as_sf(sites, coords = c("lon", "lat"), crs = 4326)

bbox <- st_bbox(sites_sf)
bbox_expanded <- bbox
bbox_expanded["xmin"] <-bbox["xmin"] - 0.007
bbox_expanded["xmax"] <-bbox["xmax"] + 0.007
bbox_expanded["ymin"] <- bbox["ymin"] - 0.007
bbox_expanded["ymax"] <- bbox["ymax"] + 0.007

bbox_expanded_sfc <- st_as_sfc(bbox_expanded)

basemap <- get_tiles(x = bbox_expanded_sfc, provider = "Esri.WorldGrayCanvas", crop = TRUE, zoom = 15)
```

```{r}
bamfield_map <- ggplot() +
  layer_spatial(basemap) +
  geom_sf(data = sites_sf, aes(color = name), size = 2.5) +
  geom_sf_text(data = sites_sf, aes(label = name), size = 3, nudge_y = 0.0009, nudge_x = 0.001) +
  coord_sf(expand = FALSE) +
  scale_color_manual(values = c("black", "black", "black")) +
  annotation_scale(location = "bl", width_hint = 0.25) +
  annotation_north_arrow(location = "tl", 
                         which_north = "true",
                         style = north_arrow_fancy_orienteering, 
                         width = unit(1, "cm"), 
                         height = unit(1, "cm")) +
  labs(x = "Longitude", y = "Latitude", title = "b) sample sites", color = NULL) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "none", 
    panel.grid.major = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.tick.x = element_line(),
    axis.line.x = element_line()
  )
```

```{r}
world_map + bamfield_map + plot_layout(ncol = 2, widths = c(1.5, 1))
```



*the lines need to be adjusted but it's a pain so i'm going to wait until i'm done messing with the plot further*

```{r}
comb_plot_2 <- ggdraw() +
  draw_plot(world_map, x = 0, y= 0, width = 0.5, height = 1) +
  draw_plot(bamfield_map, x = 0.45, y = 0, width = 0.6, height = 1) +
  draw_line(x=c(0.222, 0.665), y = c(0.45, 0.945), color = "black", size = 0.5) +
  draw_line(x=c(0.222, 0.665), y = c(0.44, 0.149), color = "black", size = 0.5) 
```


```{r}
png("C:/Users/lterp/Desktop/OneDrive - UBC/dirtnworms/dirtnworms/figures/mapfigures/mapfigureab_wline.png", width = 14, height = 6, units = "in", res = 300)
grid::grid.draw(comb_plot_2)
dev.off()
```


## attempt idk

## uses data from wesleygreentree on github thx maggie

```{r, include = FALSE}
library(sf)
library(ggplot2)
library(ggspatial)
library(patchwork)
```


```{r}
theme_map <- function(){
  theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.title = element_blank(),
          axis.text = element_text(size = 11))
}
```

```{r}
theme_inset <- function () {
  theme_bw() + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          legend.position = "none",
          plot.background = element_blank(),
          plot.margin = unit(c(0,0,0,0), "cm"),
          axis.ticks.length.x = unit(0,'pt'))
}
```

```{r}
bc.coast <- read_sf("C:/Users/lterp/Desktop/OneDrive - UBC/dirtnworms/dirtnworms/figures/mapfigures/bc-coast.shp")
st_crs(bc.coast)
```


```{r}
sites <- data.frame(
  name = c("BMSC South Dock", "West Government Dock", "Island Health Dock"),
  lon = c(-125.1378, -125.13988, -125.137045),
  lat = c(48.833226, 48.82869, 48.82711)
)

sites$lon_adj <- sites$lon - 0.0015

sites_sf_adj <- st_as_sf(sites, coords = c("lon_adj", "lat"), crs = 4326)
```

```{r}
study.area <- ggplot() +
  geom_sf(data = bc.coast) +
  geom_sf(data = sites_sf_adj, size = 3, shape = 21, fill = "steelblue", color = "black", stroke = 0.4) +
  annotate(geom = "text",
           x = -125.1343, y = 48.8345,
           label = "BMSC\nSouth Dock",
           fontface = "bold.italic",
           size = 3, colour = "black") +
  annotate(geom = "text",
           x = -125.1456, y = 48.83,
           label = "West Gov.\nDock",
           fontface = "bold.italic",
           size = 3, colour = "black") +
   annotate(geom = "text",
           x = -125.1334, y = 48.8275,
           label = "Island\nHealth Dock",
           fontface = "bold.italic",
           size = 3, colour = "black") +
  annotation_scale(width_hint = 0.35, style = "bar") +
  annotation_north_arrow(location = "tr",
                         height = unit(0.9, "cm"), width = unit(0.6, "cm"),
                         which_north = "true") +
  coord_sf(xlim = c(-125.129, -125.15), ylim = c(48.82, 48.85)) + 
  scale_x_continuous(breaks = c(-125.15, -125.14, -125.13)) +
  theme_map()
study.area
```

```{r}
bamfield.inlet <- ggplot() +
  geom_sf(data = bc.coast) +
  annotate(geom = "text",
           x = -125.15, y = 48.95,
           label = "Barkley\nSound",
           fontface = "italic",
           size = 4.2, colour = "steelblue") +
  annotate(geom = "text",
           x = -125.07, y = 48.83,
           label = "Bamfield\nInlet",
           fontface = "italic",
           size = 4.2, colour = "black") +
  annotate(geom = "rect",
           xmin = -125.13, xmax = -125.15, ymin = 48.82, ymax = 48.85, 
           fill = "transparent", colour = "black",
           linetype = "dashed") +
  annotation_scale(width_hint = 0.35, style = "bar") +
  annotation_north_arrow(location = "tr",
                         height = unit(0.9, "cm"), width = unit(0.6, "cm"),
                         which_north = "true") +
  coord_sf(xlim = c(-125.4, -125), ylim = c(48.7, 49)) + 
  theme_map()
bamfield.inlet
```

```{r}
inset <- ggplot() + 
  geom_sf(data = bc.coast, linewidth = 0.04) +
  annotate(geom = "rect",
           xmin = -125.4, xmax = -125, ymin = 48.7, ymax = 49, 
           fill = "transparent", colour = "black") +
  annotate(geom = "text",
           x = -127.5, y = 47,
           label = "Pacific\nOcean",
           fontface = "italic",
           size = 4.2, colour = "steelblue") +
  annotate(geom = "text",
           x = -124, y = 53,
           label = "British\nColumbia",
           size = 4.2, lineheight = 0.75, colour = "black") +
  annotate(geom = "text",
           x = -122, y = 46,
           label = "USA",
           size = 4.2, colour = "black") +
  coord_sf(xlim = c(-131, -120), ylim = c(45, 55)) +
  theme_inset()
inset
```



```{r}
bamfield.inlet + inset_element(inset,
                               left = -0.05, bottom = 0.4, right = 0.5, top = 1.04,
                               align_to = "panel") +
  study.area + plot_layout(ncol = 2) + plot_annotation(tag_levels = list(c("a", "b", "c")))

ggsave("figures/mapfigures/inlet-with-inset-abc.PNG", width = 20, height = 13, units = "cm", background = "white", dpi = 800)
```
```{r}
bamfield.inlet + inset_element(inset,
                               left = -0.03, bottom = 0.4, right = 0.5, top = 1.04,
                               align_to = "panel") +
  study.area + plot_layout(ncol = 2) + plot_annotation(tag_levels = list(c("a", "", "b")))

ggsave("figures/mapfigures/inlet-with-inset-ab.PNG", width = 20, height = 13, units = "cm", background = "white", dpi = 800)
```


















